import { Wifi, Utensils, Wind, Dumbbell, Shirt, Zap, Shield, Car } from 'lucide-react';

export const amenityIcons = {
  wifi: { label: 'Wi-Fi', icon: (props) => <Wifi {...props} /> },
  food: { label: 'Food', icon: (props) => <Utensils {...props} /> },
  ac: { label: 'AC', icon: (props) => <Wind {...props} /> },
  gym: { label: 'Gym', icon: (props) => <Dumbbell {...props} /> },
  laundry: { label: 'Laundry', icon: (props) => <Shirt {...props} /> },
  backup: { label: 'Power Backup', icon: (props) => <Zap {...props} /> },
  security: { label: 'Security', icon: (props) => <Shield {...props} /> },
  parking: { label: 'Parking', icon: (props) => <Car {...props} /> }
};

export const BANGALORE_LOCALITIES = [
  'AECS Layout',
  'BTM Layout',
  'Banashankari',
  'Banaswadi',
  'Bannerghatta Road',
  'Basavanagudi',
  'Bellandur',
  'Bommanahalli',
  'Brookefield',
  'CV Raman Nagar',
  'Chandra Layout',
  'Cox Town',
  'Domlur',
  'Electronic City Phase 1',
  'Electronic City Phase 2',
  'Frazer Town',
  'Giri Nagar',
  'HSR Layout',
  'HRBR Layout',
  'Hebbal',
  'Hennur',
  'Hoodi',
  'Horamavu',
  'Jayanagar',
  'JP Nagar',
  'Jalahalli',
  'Jeevanbheemanagar',
  'Kaggadasapura',
  'Kalyan Nagar',
  'Kammanahalli',
  'Kanakapura Road',
  'Kengeri',
  'Koramangala',
  'KR Puram',
  'Kumaraswamy Layout',
  'Kundalahalli',
  'Madiwala',
  'Mahadevapura',
  'Malleshwaram',
  'Marathahalli',
  'Mathikere',
  'MG Road',
  'Nagarbhavi',
  'New BEL Road',
  'RT Nagar',
  'Rajarajeshwari Nagar',
  'Rajajinagar',
  'Ramamurthy Nagar',
  'Richards Town',
  'Richmond Town',
  'SG Palya',
  'Sadashivanagar',
  'Sanjay Nagar',
  'Sarjapur Road',
  'Singasandra',
  'TC Palya',
  'Thanisandra',
  'Ulsoor',
  'Uttarahalli',
  'Vasanth Nagar',
  'Vidyaranyapura',
  'Vijayanagar',
  'Whitefield',
  'Yelahanka',
  'Yeshwanthpur'
];
